osx_image: xcode7.1
language: objective-c
xcode_project: AccessibilityAnnouncer.xcodeproj
xcode_scheme: AccessibilityAnnouncer
script: xcodebuild clean build analyze -project AccessibilityAnnouncer.xcodeproj -scheme AccessibilityAnnouncer -sdk iphonesimulator
